application: curiousmeals
version: 5
runtime: go
api_version: go1

handlers:
- url: /(.*\.(html|js|css|ico))
  static_files: static/\1
  upload: static/.*
  login: required
- url: /images/(.*)
  static_files: images/\1
  upload: images/.*
  login: required

- url: /.*
  script: _go_app
  login: required
